services:
  - type: web
    name: expense-tracker-node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: .
    autoDeploy: true


  - type: web
    name: ocrserver
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000


  - type: web
    name: apiserver
    env: docker
    dockerfilePath: ./Dockerfile.api
    envVars:
      - key: PORT
        value: 8001

